# Generated by Django 4.2.10 on 2024-05-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studenthelp', '0002_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
