# Generated by Django 4.2.10 on 2024-05-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenthelp', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='contact',
            field=models.CharField(default='default_contact', max_length=255),
        ),
        migrations.AddField(
            model_name='housing',
            name='descript',
            field=models.CharField(default='default_descript', max_length=255),
        ),
        migrations.AddField(
            model_name='transport',
            name='contact',
            field=models.CharField(default='default_contact', max_length=255),
        ),
        migrations.AddField(
            model_name='transport',
            name='depart',
            field=models.CharField(default='default_depart', max_length=255),
        ),
        migrations.AddField(
            model_name='transport',
            name='departuretime',
            field=models.CharField(default='default_departtime', max_length=255),
        ),
        migrations.AddField(
            model_name='transport',
            name='nbseats',
            field=models.IntegerField(default=0),
        ),
    ]
