# Generated by Django 4.2.10 on 2024-05-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenthelp', '0004_housing_contact_housing_descript_transport_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='nbseats',
            field=models.IntegerField(default=0),
        ),
    ]
