# Generated by Django 4.2.10 on 2024-05-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenthelp', '0005_alter_transport_nbseats'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='contact',
            field=models.CharField(default='default_contact', max_length=255),
        ),
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='internship',
            name='object',
            field=models.CharField(default='default_object', max_length=255),
        ),
    ]
