from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='studenthelp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='studenthelp/logout.html'), name='logout'),
    path('register/', views.register, name='register'),
    path('like/', views.like_post, name='like_post'),
    path('add_comment/', views.add_comment, name='add_comment'),
    path('newpost/', views.managepost, name='managepost'),
    path('newinternship/', views.manageinternship, name='manageinternship'),
    path('posts/', views.posts, name='posts'),
    path('post/<int:pk>/edit/', views.PostUpdate.as_view(), name='post_edit'),
    path('post/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('post/<int:pk>/delete/', views.PostDelete.as_view(), name='post_delete'),
    path('internships/', views.internships, name='internships'),
    path('internship/<int:pk>/edit/', views.InternshipUpdate.as_view(), name='internship_edit'),
    path('internship/<int:pk>/', views.InternshipDetail.as_view(), name='internship_detail'),
    path('internship/<int:pk>/delete/', views.InternshipDelete.as_view(), name='internship_delete'),
    path('list_events/', views.list_events, name='list_events'),
    path('create_event/', views.create_event, name='create_event'),
    path('edit_event/<int:pk>/', views.edit_event, name='edit_event'),
    path('delete_event/<int:pk>/', views.delete_event, name='delete_event'),
    path('list_housing/', views.list_housing, name='list_housing'),
    path('create_housing/', views.create_housing, name='create_housing'),
    path('edit_housing/<int:pk>/', views.edit_housing, name='edit_housing'),
    path('delete_housing/<int:pk>/', views.delete_housing, name='delete_housing'),
    path('list_recommendations/', views.list_recommendations, name='list_recommendations'),
    path('create_recommendation/', views.create_recommendation, name='create_recommendation'),
    path('edit_recommendation/<int:pk>/', views.edit_recommendation, name='edit_recommendation'),
    path('delete_recommendation/<int:pk>/', views.delete_recommendation, name='delete_recommendation'),
    path('transports/', views.list_transports, name='list_transports'),
    path('transport/new/', views.create_transport, name='create_transport'),
     path('transport/<int:pk>/edit/', views.update_transport, name='update_transport'),
    path('transport/<int:pk>/delete/', views.delete_transport, name='delete_transport'),
]
